TWITTER_EXTENSION.CONSUMER_KEY: "8AbWCDJMhLQ4wpBkbhB3wg"
TWITTER_EXTENSION.CONSUMER_SECRET: "t17ebY6Q4ib3HXpjeA3wpWhSLzSJC54gcRTw790Vg"
TWITTER_EXTENSION.OAUTH_TOKEN: "509379473-eI3mUYw64rst228Swp9vC8PIsV7gZs5bP745ENaD"
TWITTER_EXTENSION.OAUTH_TOKEN_SECRET: "MNJqyCHRTCqL9aPJC8VI0uMcbv2a9MJmvmUugWSk"
